### ISSUE TITLE
下载表结构报错

### ISSUE THREAD

**Issue by gzlance** [NewLifeX/NewLife.Cube#10]
SQLite 类型 下载表结构时报错：索引超出了数组界限。

**Comment by xxred** [comment]
下载表结构，导出表结构那也是XCode的事吧，而不是只在Cube中有问题。而且光凭这个简单的问题描述，一来不知道怎么复现错误，二来不知道问题到底出在哪个类库的哪个版本

**Comment by nnhy** [comment]
修正SQLite获取表信息时的数据索引越界错误

https://github.com/NewLifeX/X/commit/e8fb5631a9ccb1044afe0168400108828a8e80f5
