### ISSUE TITLE
登陆错误

### ISSUE THREAD

**Issue by pangmer** [NewLifeX/NewLife.Cube#15]
![yj_16q2sh w wgxb r u](https://user-images.githubusercontent.com/25192663/51320478-ed4c5800-1a9a-11e9-9294-8af4f4d72073.png)

在登陆时候遇到这个错误，数据库已经生成了数据库，是否数据库生成的表少了？
![ohkv7re1 d5vxg90x7_mbo](https://user-images.githubusercontent.com/25192663/51320378-90e93880-1a9a-11e9-81de-89446edaeb7c.jpg)

而且想自己生成user表时，发现
![y44 wt dr3g0 7r _ swe 0](https://user-images.githubusercontent.com/25192663/51320427-b70ed880-1a9a-11e9-9333-e346cbd140f6.png)
user的实体竟然是被编译过的，求指导

**Comment by nnhy** [comment]
修正魔方在SqlServer下反向工程的BUG · NewLifeX/NewLife.Cube@f36fea2
https://github.com/NewLifeX/NewLife.Cube/commit/f36fea2cb0e1016304ecf24f4c6598540af48778
