### ISSUE TITLE
PagerHelper的GetFormAction方法有错误

### ISSUE THREAD

**Issue by zilo555** [NewLifeX/NewLife.Cube#19]
第49行  var forms = new HashSet<String>(req.Form.AllKeys, StringComparer.OrdinalIgnoreCase);
第53行 foreach (var item in query.AllKeys)

这两个AllKeys在nfx里都是正常的，但是在netcore里报错，因为req.Form和query都不是NameValueCollection类型

**Comment by xxred** [comment]
这是由于PagerHelper.cs文件在之前的提交中合并了，覆盖了原来CubeNC的那份，还没有做好兼容

**Comment by xxred** [comment]
已解决
