### ISSUE TITLE
Registration prompt exception

### ISSUE THREAD

**Issue by vvvsir** [NewLifeX/NewLife.Cube#2]
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: User.Name
   在 System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
   在 XCode.DataAccessLayer.DbSession.ExecuteScalar[T](DbCommand cmd) 位置 E:\X\Src\XCode\DataAccessLayer\Common\DbSession.cs:行号 472

**Comment by nnhy** [comment]
NewLife.Cube 首次启动的时候，需要建表建库，同时初始化基础数据、权限等，多线程执行，难免出现多线程冲突导致重复添加用户的问题。根据使用经验，这个错误出现的几率大概是5%，可以无视它，重新刷新页面就可以正常使用了，后面不会出现同样问题。

**Comment by LiRazor** [comment]
1、这个错误出现的几率哪怕是1%也是BUG啊  怎么可以无视它？   
2、首次启动的时候虽然是多线程创建数据，但不等数据创建完毕就提示我这些，也不合理吧？

**Comment by nnhy** [comment]
最近几个月没有发现此类错误，也无法重现
