### ISSUE TITLE
字典参数修改报错

### ISSUE THREAD

**Issue by ritxgt008** [NewLifeX/NewLife.Cube#21]
在字典参数模块，添加一个条数据后，再对该数据进行修改，就会报错误。
数据内容为：类别（ AdminType）、名称（部门用户）、数值（3）、种类（整数），基他默认。
**报错内容：**
[NullReferenceException: 未将对象引用设置到对象的实例。]
   XCode.EntityTree`2.FindAllParents(IEntityTree entity, Boolean includeSelf) +64
   XCode.EntityTree`2.<get_AllParents>b__21_0(String e) +38
   XCode.EntityExtend.Get(String key, Func`2 func) +429
   XCode.EntityTree`2.get_AllParents() +115
   XCode.EntityTree`2.get_Deepth() +45

[TargetInvocationException: 对象“XCode.Membership.Parameter”上的属性访问器“Deepth”发生以下异常:'未将对象引用设置到对象的实例。']
   System.ComponentModel.ReflectPropertyDescriptor.GetValue(Object component) +378
   System.Web.Mvc.<>c__DisplayClass7_0.<GetPropertyValueAccessor>b__0() +18
   System.Web.Mvc.ModelMetadata.get_Model() +17
   System.Web.Mvc.DataAnnotationsModelValidator.Validate(Object container) +127
   System.Web.Mvc.<Validate>d__2.MoveNext() +216
   System.Web.Mvc.DefaultModelBinder.OnModelUpdated(ControllerContext controllerContext, ModelBindingContext bindingContext) +121
   System.Web.Mvc.DefaultModelBinder.BindComplexElementalModel(ControllerContext controllerContext, ModelBindingContext bindingContext, Object model) +68
   System.Web.Mvc.DefaultModelBinder.BindComplexModel(ControllerContext controllerContext, ModelBindingContext bindingContext) +1210
   System.Web.Mvc.DefaultModelBinder.BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext) +333
   System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor) +335
   System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +105
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__0(AsyncCallback asyncCallback, Object asyncState) +640
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +14
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +346
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_0(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +30
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +494
   System.Web.Mvc.<>c.<BeginExecute>b__151_1(AsyncCallback asyncCallback, Object callbackState, Controller controller) +16
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +20
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +403
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +16
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_0(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState) +54
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +30
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +427
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +16
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +103
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159

**Comment by ritxgt008** [comment]
引用版本：
NewLife.Core：8.1.7025.14014
NewLife.Cube：2.6.7008.35938
XCode：9.11.7025.14018

**Comment by nnhy** [comment]
这个应该是树形实体测试覆盖不周导致，现在树形实体用得越来越少

**Comment by zilo555** [comment]
在xcode源码里
XCode\Tree\EntityTree.cs
将FindAllParents方法的第一行加个try catch就不报错了
 try
{
                if (entity == null || IsNull((TKey)entity[Setting.Parent]) || entity.Parent == null) return new List<TEntity>();
            }
            catch (Exception)
            { 
                return new List<TEntity>();
            }

**Comment by nnhy** [comment]
问题已确认已修正！字典参数实体类的基类用错了，它不具备树形实体类要素。

https://github.com/NewLifeX/X/commit/617793ef36e54cb3c9720239a84c3162d5359a45
