### ISSUE TITLE
新引用NewLife.Cube,启动异常

### ISSUE THREAD

**Issue by WangBank** [NewLifeX/NewLife.Cube#22]
由于在群里没人回答，只好来这里了
admin现在刚刚引入cube的时候是被锁的，所以我用qq登陆
然后是普通游客权限，所有页面都打不开。。‘
暴力解决方法是下SQLite Expert 一个修改sqllite文件的东西，把相应的登陆着改为管理员。话说你们是故意挖的坑吗

**Comment by WangBank** [comment]
在路由集合中未能找到名为“Cube”的路由。
参数名: name
而且点击注销的时候会报这个错误

**Comment by nnhy** [comment]
魔方Cube首次启动，会初始化admin用户，默认密码admin，然后注册一个用户进去，会有一个抢管理员的过程，第一个正式进入系统的用户，会得到管理角色，并且把原来admin禁用掉。

如果你通过SSO登录，拿到的是SSO上面的普通用户角色，到了本地也是普通用户

**Comment by WangBank** [comment]
谢谢石头哥回复，那就是说最好是先注册一个用户，然后变成管理员对吗？
然后通过第三方登陆（普通用户），然后点注销的时候，会报出“在路由集合中未能找到名为“Cube”的路由。
参数名: name”这个错误，直接用用户名登陆（普通用户）再点注销话是没问题的

**Comment by nnhy** [comment]
对，最好办法是先抢占管理员！
同时，你也给了一个好的建议，我准备调整一下sso.newlifex.com，让大家默认都是管理员，这样子方便测试。
注销，的确可能有问题，测试覆盖不全面

**Comment by WangBank** [comment]
辛苦辛苦😁😁😁
