### ISSUE TITLE
魔方怎么设置三级或四级菜单

### ISSUE THREAD

**Issue by andylxy** [NewLifeX/NewLife.Cube#24]
1. 魔方默认只有二级菜单 
      区域为一级菜单，
                  控制器是二级菜单。

想知道怎么设置三级或四级菜单。

@nnhy @xxred

**Comment by xxred** [comment]
想要三级四级菜单得自己添加菜单想哦，不用自动生成，然后覆盖此文件`~\Admin\Views\Index\_Left.cshtml`自己实现

**Comment by nnhy** [comment]
魔方支持无限级菜单！
你可以在菜单表里面添加子菜单试试。

CMX里面则是标准多级菜单

**Comment by andylxy** [comment]
解决了.谢谢.. 
`\Admin\Views\Index\_Left_Item.cshtml 
 行号15代码 
` &lt;a href="#" class="dropdown-toggle"&gt;  `
href修正为@@url
` &lt;a href="@url" class="dropdown-toggle"&gt;   `

同时修正添加三级或四级菜单代码,

` @if (childs.Any())
        {
            <a href="@url" class="dropdown-toggle">
                <i class="menu-icon fa fa-caret-right"></i>
                @item.DisplayName
            </a>
            <b class="arrow"></b>
            <ul class="submenu">
                @foreach (var menu in childs)
                {
                    @Html.Partial("_Left_Item", menu);
                }
            </ul>
        }`
