### ISSUE TITLE
关于魔方源码下载后报错的问题

### ISSUE THREAD

**Issue by shiblack** [NewLifeX/NewLife.Cube#25]
之前在群里就有很多人再问这个问题，我当时用的老版本，以为是小问题就没有在意。结果我在更新到新的版本的时候也出现了这个问题，而且还找不到解决的办法。。。
下面是报错信息

未能加载文件或程序集“XCode, Version=9.11.7044.42317, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。系统找不到指定的文件
源文件: D:\NewLife.Cube\NewLife.Cube\PreApplicationStartCode.cs    行: 34 
`

if (set.SslMode >= SslModes.Full) 
HttpApplication.RegisterModule(typeof(CubeModule));
      } 
   } 
--

`
程序集加载跟踪: 下列信息有助于确定程序集“XCode, Version=9.11.7044.42317, Culture=neutral, PublicKeyToken=null”未能加载的原因。

**Comment by nnhy** [comment]
这个错误应该是引用的XCode版本不匹配所致，从nuget引用新的XCode和NewLife.Core应该可以解决问题

**Comment by shiblack** [comment]
现在Github上拉下来的Cube源码也会报这个错误，老大是不是在更新newlife的时候忘了更新xcode版本？

> 这个错误应该是引用的XCode版本不匹配所致，从nuget引用新的XCode和NewLife.Core应该可以解决问题

**Comment by xxred** [comment]
这个错误的表现是，表面看起来Nuget包还原了，运行的时候输出目录并没有引用的包。
原因不明。
解决方法是重新引用Nuget包，可先更新旧版本，在切换到新版本即可
