### ISSUE TITLE
NewLife.Cube模板修改不生效

### ISSUE THREAD

**Issue by maoshanli** [NewLifeX/NewLife.Cube#26]
问题描述： 项目环境为最新版Xcode,NewLife.Cube,NewLife.Core,运行CubeDemo，修改NewLife.Cube的login.cshtml,单独运行NewLife.Cube页面修改生效，通过项目引用NewLife.Cube的CubeDemo不生效,断点可进，但仍会加载旧的cshtml。

**Comment by xxred** [comment]
通过项目引用NewLife.Cube的CubeDemo不生效，这个问题没能重现，正常覆盖。
如果确定视图文件路径正确，依然加载旧的cshtml，可尝试清理解决方案后再试

**Comment by nnhy** [comment]
需要安装vs插件 RazorGenerator，修改cshtml时自动生成一个 xxx.cshtml.cs的文件，编译到DLL里面去

**Comment by baymaxmao** [comment]
感谢石头哥，安装插件后，问题解决

**Comment by nnhy** [comment]
可以试试 NewLife.Cube.Core，netcore3.1，不需要安装这个插件了
