### ISSUE TITLE
选中list页面数据，怎么以模态弹出显示

### ISSUE THREAD

**Issue by andylxy** [NewLifeX/NewLife.Cube#27]
![image](https://user-images.githubusercontent.com/48264964/58408745-05fbf880-80a1-11e9-9bb9-177861c12e68.png)

如上List页截图数据，以实现模态弹窗显示结果，，修改哪个地方可以实现。

![image](https://user-images.githubusercontent.com/48264964/58409076-ddc0c980-80a1-11e9-9d98-14400b3f1b32.png)

**Comment by nnhy** [comment]
这个需要修改 _List.cshtml 视图，套用某种UI，把原来的超链接 Form 修改为模态窗

**Comment by nnhy** [comment]
_List_Data_Action.cshtml  这个视图，控制了每一行最后的操作链接
