### ISSUE TITLE
字典参数 修改报错

### ISSUE THREAD

**Issue by zilo555** [NewLifeX/NewLife.Cube#28]
在xcode源码里
XCode\Tree\EntityTree.cs
将FindAllParents方法的第一行加个try catch就不报错了
 try
{
                if (entity == null || IsNull((TKey)entity[Setting.Parent]) || entity.Parent == null) return new List<TEntity>();
            }
            catch (Exception)
            { 
                return new List<TEntity>();
            }

**Comment by nnhy** [comment]
问题已确认已修正！字典参数实体类的基类用错了，它不具备树形实体类要素。
EntityTree容错能力也加强了

https://github.com/NewLifeX/X/commit/617793ef36e54cb3c9720239a84c3162d5359a45
