### ISSUE TITLE
魔方地址拦截器

### ISSUE THREAD

**Issue by andylxy** [NewLifeX/NewLife.Cube#29]
![image](https://user-images.githubusercontent.com/48264964/58688146-2fc16200-83b6-11e9-843d-4d50480b92a2.png)
例如 http://localhost:23023/Admin 
主要想实现 如图址址栏中不出现 /admin 字符 ，最后效果地址为：http://localhost:23023

**Comment by nnhy** [comment]
这个想法不错，我一下子还真没想到办法。
asp.net mvc 路由是这样写的 /{Area}/{Controller}/{Action}/{id}
然后 /Admin 的 admin 其实就是 Area，后面三个默认了 Index/Index
魔方主页路由是 /CubeHome/Index，这个页面会通过html跳转到 /Admin
你可以试试覆盖这个主页路由来达到目的
