### ISSUE TITLE
修复获取当前操作系统版本不正确

### ISSUE THREAD

**Issue by Unreal-System** [NewLifeX/NewLife.Cube#31]
https://github.com/NewLifeX/NewLife.Cube/blob/master/NewLife.Cube/Areas/Admin/Views/Index/Main.cshtml#L86 第86行换为判断.Net Framework 大于4.7.1即可更换为 @System.Runtime.InteropServices.RuntimeInformation.OSDescription 方法获取当前操作系统版本，并同时兼容.NET Framework与.NET Core 双平台 示例如下:

`if (att.FrameworkName.IndexOf("Core") > 0)
            {
                //System.Runtime.InteropServices.RuntimeInformation.OSDescription;
            }
            else if (att.FrameworkName.IndexOf("v4.7.1") > 0)
            {
                //System.Runtime.InteropServices.RuntimeInformation.OSDescription;
            }
            else if (att.FrameworkName.IndexOf("v4.7.2") > 0)
            {
                //System.Runtime.InteropServices.RuntimeInformation.OSDescription;
            }
            else if (att.FrameworkName.IndexOf("v4.8") > 0)
            {
                //System.Runtime.InteropServices.RuntimeInformation.OSDescription;
            }
            else
            { // 此时已经非.NET Core和Fx了，总不会有人去用Xamarin.Android/IOS/MAC去搭建Web平台
                //Environment.OSVersion;
            }`

[后话](https://docs.microsoft.com/zh-cn/dotnet/api/system.runtime.interopservices.runtimeinformation.osdescription?view=netframework-4.8#---)
System.Runtime.InteropServices.RuntimeInformation.OSDescription 方法适用于
.NET Core
3.0 2.2 2.1 2.0 1.1 1.0
.NET Framework
4.8 4.7.2 4.7.1
.NET Standard
2.1 2.0 1.6 1.4 1.3 1.2 1.1
Xamarin.Android
7.1
Xamarin.iOS
10.8
Xamarin.Mac
3.0

**Comment by nnhy** [comment]
还真是及时雨，我正在合并代码，今晚准备发布新版本

**Comment by Unreal-System** [comment]
飞仙那边也改一下吧

**Comment by nnhy** [comment]
今晚会发布第一个netcore版本的魔方 NewLife.Cube.Core，飞仙现在还是FX，过些天再更新
