### ISSUE TITLE
mac下新建cube core版本无法进去/admin页面

### ISSUE THREAD

**Issue by jmy10241024** [NewLifeX/NewLife.Cube#33]
### 问题截图
![Snip20191223_26](https://user-images.githubusercontent.com/26403812/71351504-cea9e780-25ae-11ea-945f-7cbeb7e3beab.png)

![@CR~7`7W}B~TX)SBURF(BM7](https://user-images.githubusercontent.com/26403812/71358128-e0958580-25c2-11ea-8e3e-1ff010c3f196.png)

### 如上图,  mac下新建了.net core mvc项目, 引入Newlife.Cube.Core后,  启动的网页后面加入/admin, 提示无此页面, .net framework下网站能正确显示

**Comment by nnhy** [comment]
已修改后台首页为 /admin
