### ISSUE TITLE
core版本上传文件, 文件大小比较大的时候有问题

### ISSUE THREAD

**Issue by jmy10241024** [NewLifeX/NewLife.Cube#34]
### 1. 操作流程截图
![Snip20191224_12](https://user-images.githubusercontent.com/26403812/71393314-fba9d900-2646-11ea-9845-ae61ab08ea08.png)
![Snip20191224_13](https://user-images.githubusercontent.com/26403812/71393323-ffd5f680-2646-11ea-888b-e42ad04b2e83.png)
![Snip20191224_14](https://user-images.githubusercontent.com/26403812/71393325-02385080-2647-11ea-823f-07748b38f926.png)
![Snip20191224_15](https://user-images.githubusercontent.com/26403812/71393326-03697d80-2647-11ea-881a-178989c2fed8.png)
### 2. 在程序中已经加入了文件大小的限制为6G
代码如下
![Snip20191224_16](https://user-images.githubusercontent.com/26403812/71393354-2005b580-2647-11ea-9838-9f979a372b78.png)
### 3. 使用的是NewLife.Cube.core     .net mvc core

**Comment by nnhy** [comment]
打开日志，看看这个问题是由于什么限制造成

**Comment by nnhy** [comment]
魔方作为一个组件引入项目里面，可以在最终应用项目里面增加这个设置
