### ISSUE TITLE
模板覆盖部分生效问题

### ISSUE THREAD

**Issue by 31833077** [NewLifeX/NewLife.Cube#36]
魔方视图   覆盖失败  webconfig已经添加程序集  视图也导出了  覆盖无效
在根目录/views覆盖生效
在Areas/area/views覆盖无效   
RazorGenerator 已经安装并生成Generator.cs文件

**Comment by xxred** [comment]
检查视图路径是否正确，通过页面高级操作，生成页面，查看生成页面路径
