### ISSUE TITLE
netcore下高级功能生成视图报错且生成的路径不对

### ISSUE THREAD

**Issue by zilo555** [NewLifeX/NewLife.Cube#37]
魔方 高级功能 生成表单 列表 搜索时报错

依据报错内容 新建文件夹后，实际生成路径不对

**Comment by nnhy** [comment]
魔方根据项目名自动探测源码所在位置，可能导致生成表单列表等页面的目录不正确，需要手工拷贝。
NETCore中，在运行目录与源码目录不一致时，该问题一定存在。
该功能早期设计于nfx，则完全没有问题，因为就是同一个目录。
