### ISSUE TITLE
1111版本编译时缺少Build.cs

### ISSUE THREAD

**Issue by Xusp** [NewLifeX/NewLife.Cube#39]
在拉取最新的1111版本后，编译项目时报错，分别缺少Build.cs 和Build_netcore.cs文件。
————
错误	CS2001	未能找到源文件“E:\Git Repository\Newlife\NewLife.Cube\NewLife.Cube\Entity\Build.cs”。	NewLife.Cube	E:\Git Repository\Newlife\NewLife.Cube\NewLife.Cube\CSC	1	活动
错误	CS2001	未能找到源文件“E:\Git Repository\Newlife\NewLife.Cube\NewLife.Cube\Entity\Build_netcore.cs”。	NewLife.Cube	E:\Git Repository\Newlife\NewLife.Cube\NewLife.Cube\CSC	1	活动

**Comment by nnhy** [comment]
删了这个文件再编译就好
