### ISSUE TITLE
请教：第三方登录应该如何配置呢？

### ISSUE THREAD

**Issue by hebiziyu** [NewLifeX/NewLife.Cube#41]
能否给一个demo，比如微信登录该如何配置呢？
多谢

**Comment by nnhy** [comment]
修改配置文件 Config/OAuth.config ，Name=WeiXin 那一行

**Comment by hebiziyu** [comment]
感谢您的答复，这里有一个参数不知道该怎么填写，麻烦指点下： AccessServer 这个该怎么填写？
<OAuthItem Name="Weixin" Server="http://localhost:3556/sso" AccessServer="" AppID="wx9cd2522eceba1168" Secret="5fcb927f19282c438tt9f7885719a2f3" Scope="snsapi_userinfo" />
再次感谢

**Comment by hebiziyu** [comment]
OAuthItem Name="Weixin" Server="http://localhost:3556/sso" AccessServer="" AppID="wx9cd3522ecebf1168" Secret="5fcb927f19272c438fb9f7885719a2f3" Scope="snsapi_userinfo"

**Comment by nnhy** [comment]
AccessServer 默认可以为空，使用前面那个地址。
这个地址用于App拿到跳转回来的code后，直接访问ssoServer，换取AccessToken等信息。
Server一般配置为公网跳转地址，如果App和ssoServer部署在同一个内网，那么AccessServer可以指定为ssoServer的内网地址，就没必要走公网绕一趟了
