### ISSUE TITLE
建议增加Bootstrap Table扩展

### ISSUE THREAD

**Issue by lkicesky** [NewLifeX/NewLife.Cube#43]
建议增加Bootstrap Table扩展，里面有很多实用的固定表头、多行选中变色等功能

**Comment by nnhy** [comment]
覆盖重写 _List_Data.cshtml  视图即可！

1. 新建aspnetcore项目，新建目录 /Views/Shared/
2. 从魔方的这个位置拷贝 _List_Data.cshtml  文件到 新建目录的该位置
3. 修改该位置的 _List_Data.cshtml，内部table改为自己想要的表格实现
