### ISSUE TITLE
菜单乱码

### ISSUE THREAD

**Issue by gainorloss** [NewLifeX/NewLife.Cube#44]
![image](https://user-images.githubusercontent.com/26458238/115980937-f655f900-a5c2-11eb-97c4-00c0b5305c5b.png)
 尚未设置本地化

```
//依然失败
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance)
```

**Comment by nnhy** [comment]
这是什么环境的操作系统？

你可以看看魔方演示站（洛杉矶），http://lg.newlifex.com/
这是海外英文系统，直接编译cube源码部署

**Comment by gainorloss** [comment]
windows10 本机 调试启动的，比较奇怪

**Comment by nnhy** [comment]
这个没有遇到过，是不是系统打过补丁没重启？更多的我也想不到了，需要见招拆招

**Comment by YIGENB** [comment]
英文系统或linux  创建数据库的时候需要指定字符集
create database 数据库名  collate Chinese_PRC_CI_AS
