### ISSUE TITLE
魔方ECharts图表构建时未处理Items扩展属性，导致不能对图表进行更多的自定义操作

### ISSUE THREAD

**Issue by Xusp** [NewLifeX/NewLife.Cube#45]
如题。石头兄，ECharts类的Build方法未处理Items扩展属性，添加进去的自定义属性不能使用。

**Comment by nnhy** [comment]
我尽快检查处理

**Comment by nnhy** [comment]
已确认存在该问题，已修复！

https://github.com/NewLifeX/NewLife.Cube/commit/2de82d8552d0995d291b364f7eeda75679b87ca3
