### ISSUE TITLE
切换主题后，登录界面错乱

### ISSUE THREAD

**Issue by yangchongyuan** [NewLifeX/NewLife.Cube#47]
![20210818123224](https://user-images.githubusercontent.com/44629286/129837409-dc9a8016-9f8f-44f5-b640-cd3dc9042473.png)

**Comment by yangchongyuan** [comment]
master分支代码，切换的是Metronic主题

**Comment by nnhy** [comment]
应该是metronic的登录页皮肤还没有调整好
