### ISSUE TITLE
NewLife.CubeNC 登陆后无法获取用户名

### ISSUE THREAD

**Issue by rqx110** [NewLifeX/NewLife.Cube#5]
NewLife.CubeNC登录之后，无法拿到登录用户。以下user一直返回null
https://github.com/NewLifeX/NewLife.Cube/blob/66c3b7280645cdd018e4f4505523f8f7f9c8ff78/NewLife.CubeNC/Com/MembershipExtensions.cs#L77

**Comment by nnhy** [comment]
@xxred 笑笑同学来解决这个问题
