### ISSUE TITLE
datetime in mssql is not support  new DateTime(1, 1, 2),

### ISSUE THREAD

**Issue by xueshaoyu** [NewLifeX/NewLife.Cube#51]
a bug  from method
 public UserOnline SetStatus(String sessionid, String page, String status, UserAgentParser userAgent, Int32 userid = 0, String name = null, String ip = null) 
 in this file UserService.cs  
code like:
LastError = new DateTime(1, 1, 2),

**Comment by nnhy** [comment]
修复在设置用户在线情况时MSSql不能使用1973年之前的日期的bug · NewLifeX/NewLife.Cube@cb1b5f2
https://github.com/NewLifeX/NewLife.Cube/commit/cb1b5f27bab04f3aa881337b6c324fa08418b099
