### ISSUE TITLE
怎么跟blazor对接？

### ISSUE THREAD

**Issue by jingshui127** [NewLifeX/NewLife.Cube#53]
能不能出个简单的文档或者配置实例？

**Comment by nnhy** [comment]
最新的 readme.md 有介绍第三代魔方接口

**Comment by nnhy** [comment]
接口文档： https://cube3.newlifex.com
接口说明： https://github.com/NewLifeX/NewLife.Cube/blob/master/README.md
Blazor魔方：https://github.com/NewLifeX/NewLife.CubeBlazor
