### ISSUE TITLE
魔方具体应用的一些问题

### ISSUE THREAD

**Issue by Xusp** [NewLifeX/NewLife.Cube#7]
1.魔方中有没有办法进行横切编程，例如我要给所有的控制器的动作方法加上统一的数据权限，或者讲解一下在魔方中实现多租户的思路。
2.请补充讲解一下集成第3方登录以及SSO在魔方中的应用，例如部署自己的SSO服务器。
3.控制器在魔方中想自动注册为不可见，应该如何配置？

**Comment by xxred** [comment]
> 1.魔方中有没有办法进行横切编程，例如我要给所有的控制器的动作方法加上统一的数据权限，或者讲解一下在魔方中实现多租户的思路。
- 可以用过滤器实现
> 2.请补充讲解一下集成第3方登录以及SSO在魔方中的应用，例如部署自己的SSO服务器。
- 只需要配置自己的应用id即可，跑一次之后会出现`Config/OAuth.config`
> 3.控制器在魔方中想自动注册为不可见，应该如何配置？
```csharp
        /// <summary>菜单不可见</summary>
        /// <param name="menu"></param>
        /// <returns></returns>
        protected override IDictionary<MethodInfo, Int32> ScanActionMenu(IMenu menu)
        {
            if (menu.Visible)
            {
                menu.Visible = false;
                (menu as IEntity).Save();
            }

            return base.ScanActionMenu(menu);
        }
```

**Comment by Xusp** [comment]
明白了，十分感谢！
