### ISSUE TITLE
下拉框考虑不同的登陆用户显示不同的内容怎么操作。

### ISSUE THREAD

**Issue by zhangdachen** [NewLifeX/NewLife.Cube#8]
下拉框考虑不同的登陆用户显示不同的内容怎么操作。

**Comment by Xusp** [comment]
我的理解是：可以根据不同的用户在高级查询中进行查询，需要在项目一级统一相应的操作。

**Comment by xxred** [comment]
下拉框内容如果是后台生成的那就直接修改视图，也就是模板覆盖。如果是自己请求得来的数据，自己做好权限过滤
