### ISSUE TITLE
新增角色，设置为禁用系统不可用，新增编辑用户时仍可以选择该角色

### ISSUE THREAD

**Issue by zxingdream** [NewLifeX/NewLife.Cube#88]
![5551204d946f3281ec01cde29ae0fdf](https://github.com/NewLifeX/NewLife.Cube/assets/12619680/70302e43-f442-4c77-82e8-9d40ebfb7a96)
![796b096ba03c4515cb73ff71067f409](https://github.com/NewLifeX/NewLife.Cube/assets/12619680/044fb325-db74-43b1-9e10-860de4c3708b)

**Comment by xcl-net** [comment]
角色和角色组禁用的过滤掉设置
![角色和角色组禁用的过滤掉设置](https://github.com/NewLifeX/NewLife.Cube/assets/15728845/b9fda479-d4cf-4239-b496-d88e45120237)
