### ISSUE TITLE
.NetCore版本中关于注入使用的讨论

### ISSUE THREAD

**Issue by xxred** [NewLifeX/NewLife.Cube#9]
魔方的 .Net Core版本已经迁移过来，但是仍然保留大量以前的用法，这跟Core推崇的依赖注入用法格格不入。现在使用的对象容器源于XCode，2011年开始使用，已经很老了。萌新同学提出了此问题，确实是个需要正视的问题。现在面临的问题就是：继续使用对象容器，还是全面改成Core那样的写法。

讨论范围不仅限于魔方Cube，同时涉及到XCode。在这里讨论此问题，大家有好的想法或者解决方案可以在此提出，大家共同讨论。

**Comment by YannKing** [comment]
确实很另类 导致学习core的时候 不敢用X组件。

**Comment by nnhy** [comment]
.net版XCode要用IoC，你们打算怎么改？总不能为了netcore的对象容器，然后就不支持.net版了吧

**Comment by htrlq** [comment]
我以为改造core是一个结构调整，仿微软官方的asp.net core一样，把程序结构调整成轻量级的，依赖注入统一入口和用法。包括兼容fx我有一点见解，这个di容器由我们管理，内部区分core和fx，走双分支的实现，以预编译指令的形式

**Comment by muxhub** [comment]
> .net版XCode要用IoC，你们打算怎么改？总不能为了netcore的对象容器，然后就不支持.net版了吧

NET版本迟早要不支持（应该不远），可以从现在开始优化Core版本，放慢NET的脚步，留一个最终LTS版本，开始Core版本

**Comment by Godricm** [comment]
AutoFac就是个很不错的选择呀

**Comment by Xusp** [comment]
@nnhy 可考虑在X组件层面抽象一个统一IoC的接口，至于使用哪个IoC组件，像数据库驱动一样配置一下就行了，后面爱用什么就用什么。这样应该不难，关键是对NewLife.Core和XCode组件里面已有实现改动的工作量很大，不过您可以定义好接口和任务，在群里由有时间有能力的大侠认领即可：）

**Comment by nnhy** [comment]
> @nnhy 可考虑在X组件层面抽象一个统一IoC的接口，至于使用哪个IoC组件，像数据库驱动一样配置一下就行了，后面爱用什么就用什么。这样应该不难，关键是对NewLife.Core和XCode组件里面已有实现改动的工作量很大，不过您可以定义好接口和任务，在群里由有时间有能力的大侠认领即可：）

那样改动可不小，并且怎么样做完整测试确保可靠性？

**Comment by xxred** [comment]
统一使用IoC目前先从Cube开始，大部分功能已从XCode下沉到Cube，现已可以在Cube全面使用Ioc。未来预计可以在X组件实现IoC，这样可以外部替换X组件的Ioc，或者X组件的Ioc替换Core的IoC

**Comment by Xusp** [comment]
@xxred 这种渐进的方式很不错，不至于大规模进行修改，而且在运用的过程中还可以对有关设计进行检讨，有利于今后XCode、Core等核心组件对IoC的引入。我个人认为对于IoC部分可以在核心组件定义好以下组件，后面再配合不同的实现就可以实现不同IoC组件在X组件核心库的配置或替换使用，就像上面提到的XCode组件的数据库驱动一样。
1、IServiceRegister 用于对服务或对象的注册工作；
2、IServiceResoler 用于从对象容器中解析服务或对象，这两个接口也可以考虑合并；
3、Lifetime枚举，定义服务在系统中的生命周期。
我的代码能力相当有限，一直在使用大石头这套框架，一时还没有能力贡献代码，所以只能提一些想法，希望可以多向各位学习。

**Comment by nnhy** [comment]
X组件自带ioc/ObjectContainer其实就是一个大字典，前期支持过当下最热门构造函数注入，甚至还有属性注入，后来一年时间里面，存在大量争议，遂废除相关支持，仅保留核心字典，Register和Resolve

未来的发展方向如何，暂时不得而已，但是有一点可以肯定，X组件会逐步减少使用ioc。
经过10多年的使用经验积累发现，造就很多接口，配合ioc，本来就是为了方便用户扩展相关功能。然而实际上，根本就不是这样，10多年时间里几乎从未发现有人扩展局部功能然后通过ioc实现注入。所有需要对组件进行扩展的场景，大家都是通过接口重新实现，对象赋值，甚至直接修改源码来实现。大大出乎意料。

因此，未来需要扩展的地方，都会使用接口，然后内置一个默认实现，允许外部重载覆盖。

**Comment by chenqilscy** [comment]
设计一个ioc的接口，定义注入和解析的函数。启动时，根据环境加载对应的ioc实现。接口初始化时，就是一个全局的静态变量，后面使用接口去注入和解析。

**Comment by xxred** [comment]
ioc，本来就是为了方便用户扩展相关功能。大家可以不用但是不能没有，等想替换拓展功能的时候，发现写死了。这时候最方便的就是重新实现接口再对象赋值，要不然就是修改源码来实现，除此之外就是放弃使用。有精力自己维护的就修改源码维护独立分支了，而大部分人仍然使用默认实现就可以了，可能偶尔想到拓展后面又憋回去了。

如果在以前，这一切看似很合理很正常，因为asp net mvc框架也是大量使用静态变量，对象赋值，大家也习惯这么用。但是asp net core发布了，这一切慢慢发生了变化。大部分人还是很喜欢这种模式的，也在慢慢熟悉注入，理解依赖注入。

所以，我认为现在是个很好的时机，大量使用构造函数注入，以前的讨论和争议不得而知，现在和未来充满了挑战和希望。

另外，我觉得不是没有人通过ioc注入拓展功能，而是太难拓展没有文档指导，或者根本就是写死了无法拓展。

**Comment by nnhy** [comment]
对象容器ObjectContainer · 语雀
https://www.yuque.com/smartstone/nx/object_container
